import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// The palettes the user can pick between.
enum AppColorScheme {
  /// The original look: teal, generated by Material from a seed colour.
  synchronizer('Synchronizer'),

  /// Colourless and pure black, so an OLED panel can switch those pixels off.
  oled('OLED'),

  /// Ubuntu-flavoured greys, sitting between light and dark.
  yaru('Yaru');

  const AppColorScheme(this.label);
  final String label;
}

/// Appearance and startup preferences. A [ChangeNotifier] because changing any
/// of these has to rebuild the app above [MaterialApp], not just one screen.
///
/// How changes are applied (the plain-sync switch) stays in [SyncSettings],
/// which the sync screen reads at the moment it needs it.
class AppSettings extends ChangeNotifier {
  static const _schemeKey = 'color_scheme';
  static const _themeModeKey = 'theme_mode';

  AppColorScheme _scheme = AppColorScheme.synchronizer;
  ThemeMode _themeMode = ThemeMode.system;

  AppColorScheme get scheme => _scheme;
  ThemeMode get themeMode => _themeMode;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _scheme = _byName(
      AppColorScheme.values,
      prefs.getString(_schemeKey),
      AppColorScheme.synchronizer,
    );
    _themeMode = _byName(
      ThemeMode.values,
      prefs.getString(_themeModeKey),
      ThemeMode.system,
    );
    notifyListeners();
  }

  Future<void> setScheme(AppColorScheme value) async {
    if (value == _scheme) return;
    _scheme = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_schemeKey, value.name);
  }

  Future<void> setThemeMode(ThemeMode value) async {
    if (value == _themeMode) return;
    _themeMode = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_themeModeKey, value.name);
  }

  /// Reads an enum back by name, falling back if it was never stored or the
  /// stored value no longer exists.
  static T _byName<T extends Enum>(List<T> values, String? name, T fallback) {
    for (final value in values) {
      if (value.name == name) return value;
    }
    return fallback;
  }
}
