import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// The palettes the user can pick between.
enum AppColorScheme {
  /// The original look: teal, generated by Material from a seed colour.
  synchronizer('Synchronizer'),

  /// Colourless and pure black, so an OLED panel can switch those pixels off.
  oled('OLED'),

  /// Ubuntu-flavoured greys, sitting between light and dark.
  yaru('Yaru');

  const AppColorScheme(this.label);
  final String label;
}

/// The languages the user can pick between, plus following the system.
///
/// Named in their own language, the way every other app lists them: someone who
/// switched to the wrong one has to find their way back, and "Russian" is no
/// help if you cannot read it.
enum AppLanguage {
  system(null, 'System'),
  english(Locale('en'), 'English'),
  russian(Locale('ru'), 'Русский');

  const AppLanguage(this.locale, this.label);

  /// The locale to force, or null to follow the system.
  final Locale? locale;
  final String label;
}

/// Appearance and startup preferences. A [ChangeNotifier] because changing any
/// of these has to rebuild the app above [MaterialApp], not just one screen.
///
/// How changes are applied (the plain-sync switch) stays in [SyncSettings],
/// which the sync screen reads at the moment it needs it.
class AppSettings extends ChangeNotifier {
  static const _schemeKey = 'color_scheme';
  static const _themeModeKey = 'theme_mode';
  static const _languageKey = 'language';

  AppColorScheme _scheme = AppColorScheme.synchronizer;
  ThemeMode _themeMode = ThemeMode.system;
  AppLanguage _language = AppLanguage.system;

  AppColorScheme get scheme => _scheme;
  ThemeMode get themeMode => _themeMode;
  AppLanguage get language => _language;

  /// The locale to force, or null to follow the system - which is what
  /// [MaterialApp.locale] wants: null there means "decide from the platform".
  Locale? get locale => _language.locale;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _scheme = _byName(
      AppColorScheme.values,
      prefs.getString(_schemeKey),
      AppColorScheme.synchronizer,
    );
    _themeMode = _byName(
      ThemeMode.values,
      prefs.getString(_themeModeKey),
      ThemeMode.system,
    );
    _language = _byName(
      AppLanguage.values,
      prefs.getString(_languageKey),
      AppLanguage.system,
    );
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage value) async {
    if (value == _language) return;
    _language = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, value.name);
  }

  Future<void> setScheme(AppColorScheme value) async {
    if (value == _scheme) return;
    _scheme = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_schemeKey, value.name);
  }

  Future<void> setThemeMode(ThemeMode value) async {
    if (value == _themeMode) return;
    _themeMode = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_themeModeKey, value.name);
  }

  /// Reads an enum back by name, falling back if it was never stored or the
  /// stored value no longer exists.
  static T _byName<T extends Enum>(List<T> values, String? name, T fallback) {
    for (final value in values) {
      if (value.name == name) return value;
    }
    return fallback;
  }
}
